import cron from "node-cron";
import Audio from "../models/audio";
import AutoGeneratedPlaylist from "../models/autoGeneratedPlaylist";
import measurement from "../constants/measurement";

const generatePlaylist = async () => {
  const audios = await Audio.aggregate([
    {
      $sort: {
        likes: -1,
      },
    },
    {
      $sample: {
        size: 20,
      },
    },
    {
      $group: {
        _id: "$category",
        audios: {
          $push: "$$ROOT._id",
        },
      },
    },
  ]);

  audios.map(async (item) => {
    await AutoGeneratedPlaylist.updateOne(
      { title: item._id },
      { $set: { items: item.audios } },
      { upsert: true }
    );
  });
};

cron.schedule(measurement.ONE_DAY_IN_CRON, async () => {
  await generatePlaylist();
});
